"""
ChestGuard NeuralScan — Report Generation Routes
"""
import tempfile
from datetime import datetime
from flask import Blueprint, request, jsonify, send_file, session
from fpdf import FPDF

report_bp = Blueprint("report", __name__)


@report_bp.route("/api/report/pdf", methods=["POST"])
def generate_pdf():
    """
    Generate and download a PDF report.
    Accepts: JSON with analysis results.
    Returns: PDF file download.
    """
    data = request.get_json()
    if not data:
        return jsonify({"error": "No data provided"}), 400

    try:
        results = data.get("predictions", {})
        neural_score = data.get("neural_score", {})
        patient_info = data.get("patient_info", {})
        pipeline = data.get("pipeline", {})
        regions = data.get("regions", {})

        pdf = FPDF()
        pdf.add_page()

        # ── Header ──
        pdf.set_fill_color(79, 70, 229)
        pdf.rect(0, 0, 210, 45, "F")
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Arial", "B", 28)
        pdf.cell(0, 20, "ChestGuard NeuralScan", ln=True, align="C")
        pdf.set_font("Arial", "I", 12)
        pdf.cell(0, 8, "AI-Powered Chest X-Ray Diagnostic Intelligence Report", ln=True, align="C")
        pdf.set_font("Arial", "", 9)
        pdf.cell(0, 8, f"Generated: {datetime.now().strftime('%B %d, %Y at %H:%M')}", ln=True, align="C")

        pdf.set_text_color(0, 0, 0)
        pdf.ln(10)

        # ── Patient Information ──
        pdf.set_font("Arial", "B", 14)
        pdf.set_fill_color(240, 240, 250)
        pdf.cell(0, 10, "  Patient Information", ln=True, fill=True)
        pdf.set_font("Arial", "", 11)
        pdf.ln(3)
        pdf.cell(95, 7, f"  Age: {patient_info.get('age', 'N/A')}")
        pdf.cell(95, 7, f"Gender: {patient_info.get('gender', 'N/A')}", ln=True)
        pdf.cell(95, 7, f"  Smoking: {patient_info.get('smoking', 'N/A')}")
        pdf.cell(95, 7, f"Symptoms: {patient_info.get('symptoms', 'N/A')}", ln=True)
        pdf.cell(0, 7, f"  Conditions: {patient_info.get('conditions', 'N/A')}", ln=True)
        pdf.ln(5)

        # ── NeuralScore ──
        score = neural_score.get("score", 0)
        tier = neural_score.get("tier", {}).get("level", "Unknown")
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, f"  NeuralScore: {score}/100 ({tier} Risk)", ln=True, fill=True)
        pdf.ln(3)

        # Score breakdown
        pdf.set_font("Arial", "", 10)
        breakdown = neural_score.get("breakdown", {})
        for key, data in breakdown.items():
            pdf.cell(0, 6, f"    {data.get('label', key)}: {data.get('score', 0)}/100 (weight: {data.get('weight', 0)})", ln=True)
        pdf.ln(5)

        # ── Top Findings ──
        pdf.set_font("Arial", "B", 14)
        pdf.cell(0, 10, "  X-Ray Analysis Results (Top 5)", ln=True, fill=True)
        pdf.set_font("Arial", "", 11)
        pdf.ln(3)
        for i, (disease, prob) in enumerate(list(results.items())[:5]):
            pdf.cell(0, 7, f"    {i+1}. {disease}: {prob}%", ln=True)
        pdf.ln(5)

        # ── Regional Analysis ──
        if regions:
            pdf.set_font("Arial", "B", 14)
            pdf.cell(0, 10, "  Regional Analysis", ln=True, fill=True)
            pdf.set_font("Arial", "", 10)
            pdf.ln(3)
            for region_name, region_info in regions.items():
                status = region_info.get("status", "N/A")
                health = region_info.get("health_score", "N/A")
                pdf.cell(0, 6, f"    {region_name}: Health {health}% - Status: {status.upper()}", ln=True)
            pdf.ln(5)

        # ── Agent Analysis ──
        agents = pipeline.get("agents", [])
        for agent_data in agents:
            pdf.add_page()
            agent_name = agent_data.get("agent", "Agent")
            pdf.set_font("Arial", "B", 14)
            pdf.set_fill_color(240, 240, 250)
            pdf.cell(0, 10, f"  {agent_data.get('icon', '')} {agent_name}", ln=True, fill=True)
            pdf.set_font("Arial", "", 10)
            pdf.ln(3)

            output = agent_data.get("output", "")
            # Clean for PDF encoding
            clean_output = output.encode("latin-1", "replace").decode("latin-1")
            pdf.multi_cell(0, 5, clean_output)
            pdf.ln(5)

        # ── Disclaimer ──
        pdf.add_page()
        pdf.set_font("Arial", "B", 14)
        pdf.set_fill_color(255, 243, 205)
        pdf.cell(0, 10, "  DISCLAIMER", ln=True, fill=True)
        pdf.set_font("Arial", "I", 9)
        pdf.ln(3)
        pdf.multi_cell(0, 5,
            "This report is generated by ChestGuard NeuralScan, an AI-powered screening system. "
            "It is intended for preliminary screening purposes ONLY and does NOT constitute a "
            "medical diagnosis. The NeuralScore, risk assessments, and recommendations are "
            "algorithmically generated and should be validated by a qualified healthcare "
            "professional. Do not make medical decisions based solely on this report. "
            "Always consult a licensed physician for proper diagnosis and treatment planning."
        )

        # Save
        temp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
        pdf.output(temp_file.name)

        return send_file(
            temp_file.name,
            mimetype="application/pdf",
            as_attachment=True,
            download_name=f"ChestGuard_Report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        )

    except Exception as e:
        return jsonify({"error": f"Report generation failed: {str(e)}"}), 500
